<a href="https://colab.research.google.com/github/durgeshwagh14/procurement-strategy-predictor/blob/main/ML_Repeat_Day_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Procurement Strategy Predictor**

In [82]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score , classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
import pickle

In [24]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shahriarkabir/procurement-strategy-dataset-for-kraljic-matrix")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'procurement-strategy-dataset-for-kraljic-matrix' dataset.
Path to dataset files: /kaggle/input/procurement-strategy-dataset-for-kraljic-matrix

In [25]:
df = pd.read_csv(path + "/realistic_kraljic_dataset.csv")
df.head(5)

,Product_ID,Product_Name,Supplier_Region,Lead_Time_Days,Order_Volume_Units,Cost_per_Unit,Supply_Risk_Score,Profit_Impact_Score,Environmental_Impact,Single_Source_Risk,Kraljic_Category
0,P001,Semiconductors,South America,81,171,255.03,5,5,4,Yes,Strategic
1,P002,Semiconductors,South America,8,763,380.33,5,4,4,Yes,Strategic
2,P003,Pharma APIs,Asia,65,413,385.24,4,5,5,Yes,Strategic
3,P004,Semiconductors,South America,70,882,287.64,5,5,5,Yes,Strategic
4,P005,Lithium Batteries,Asia,15,120,382.26,4,4,4,Yes,Strategic

In [26]:
df["Kraljic_Category"].value_counts()

Kraljic_Category
Strategic       250
Bottleneck      250
Leverage        250
Non-Critical    250
Name: count, dtype: int64

In [44]:
df["Supplier_Region"].value_counts()

Supplier_Region
Asia             269
Global           250
Europe           226
North America     96
Africa            83
South America     76
Name: count, dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   object
 1   Product_Name          1000 non-null   object
 2   Supplier_Region       1000 non-null   object
 3   Lead_Time_Days        1000 non-null   int64
 4   Order_Volume_Units    1000 non-null   int64
 5   Cost_per_Unit         1000 non-null   float64
 6   Supply_Risk_Score     1000 non-null   int64
 7   Profit_Impact_Score   1000 non-null   int64
 8   Environmental_Impact  1000 non-null   int64
 9   Single_Source_Risk    1000 non-null   object
 10  Kraljic_Category      1000 non-null   object
dtypes: float64(1), int64(5), object(5)
memory usage: 86.1+ KB

In [28]:
df["Single_Source_Risk"] = df["Single_Source_Risk"].map({"No": 0, "Yes": 1})

In [30]:
df.head(10)

,Product_ID,Product_Name,Supplier_Region,Lead_Time_Days,Order_Volume_Units,Cost_per_Unit,Supply_Risk_Score,Profit_Impact_Score,Environmental_Impact,Single_Source_Risk,Kraljic_Category
0,P001,Semiconductors,South America,81,171,255.03,5,5,4,1,Strategic
1,P002,Semiconductors,South America,8,763,380.33,5,4,4,1,Strategic
2,P003,Pharma APIs,Asia,65,413,385.24,4,5,5,1,Strategic
3,P004,Semiconductors,South America,70,882,287.64,5,5,5,1,Strategic
4,P005,Lithium Batteries,Asia,15,120,382.26,4,4,4,1,Strategic
5,P006,AI Chips,Asia,84,466,405.27,5,5,5,1,Strategic
6,P007,Lithium Batteries,South America,69,101,398.76,5,4,5,1,Strategic
7,P008,AI Chips,South America,68,369,481.85,5,4,4,0,Strategic
8,P009,Pharma APIs,Asia,35,978,424.20,3,4,4,1,Strategic
9,P010,Semiconductors,Africa,87,620,204.69,5,5,5,1,Strategic

In [39]:
x = df.drop(["Product_ID","Supplier_Region","Product_Name", "Kraljic_Category"], axis=1)
y = df["Kraljic_Category"]

In [76]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [77]:
# Call the model

model_knn = KNeighborsClassifier()
model_nb = GaussianNB()
model_lr = LogisticRegression()
model_svm = SVC()

In [78]:
model_knn.fit(x_train,y_train)
model_nb.fit(x_train,y_train)
model_lr.fit(x_train,y_train)
model_svm.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

SVC()

In [79]:
y_pred_knn = model_knn.predict(x_test)
y_pred_nb = model_nb.predict(x_test)
y_pred_lr = model_lr.predict(x_test)
y_pred_svm = model_svm.predict(x_test)

In [80]:
print("KNN Report :\n",classification_report(y_test,y_pred_knn))
print("Navie Report :\n",classification_report(y_test,y_pred_nb))
print("Logistic Report :\n",classification_report(y_test,y_pred_lr))
print("SVM Report :\n",classification_report(y_test,y_pred_svm))

KNN Report :
               precision    recall  f1-score   support

  Bottleneck       0.82      0.94      0.88        52
    Leverage       0.87      0.85      0.86        55
Non-Critical       0.84      0.86      0.85        49
   Strategic       0.92      0.75      0.82        44

    accuracy                           0.85       200
   macro avg       0.86      0.85      0.85       200
weighted avg       0.86      0.85      0.85       200

Navie Report :
               precision    recall  f1-score   support

  Bottleneck       0.98      1.00      0.99        52
    Leverage       1.00      1.00      1.00        55
Non-Critical       1.00      1.00      1.00        49
   Strategic       1.00      0.98      0.99        44

    accuracy                           0.99       200
   macro avg       1.00      0.99      0.99       200
weighted avg       1.00      0.99      0.99       200

Logistic Report :
               precision    recall  f1-score   support

  Bottleneck       0.88      0.94      0.91        52
    Leverage       0.98      0.96      0.97        55
Non-Critical       0.96      0.98      0.97        49
   Strategic       0.93      0.84      0.88        44

    accuracy                           0.94       200
   macro avg       0.94      0.93      0.93       200
weighted avg       0.94      0.94      0.93       200

SVM Report :
               precision    recall  f1-score   support

  Bottleneck       0.71      1.00      0.83        52
    Leverage       0.78      0.89      0.83        55
Non-Critical       0.95      0.71      0.81        49
   Strategic       0.85      0.52      0.65        44

    accuracy                           0.80       200
   macro avg       0.82      0.78      0.78       200
weighted avg       0.82      0.80      0.79       200

In [84]:
# test the model
scores = {
    "KNN": model_knn.score(x_test, y_test),
    "Logistic Regression": model_lr.score(x_test, y_test),
    "SVM": model_svm.score(x_test, y_test)
}

best_model = max(scores, key=scores.get)
print(f"\n✅ Best Model is: {best_model} with Accuracy = {scores[best_model]:.2f}")

✅ Best Model is: Logistic Regression with Accuracy = 0.94

In [85]:
# Create a PKL file
with open('Procurement.pkl', 'wb') as f:
    pickle.dump(model_lr, f)